from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CategoryNamesMainWindow(object):
    def setupCategoryNamesUi(self, CategoryNamesMainWindow):
        CategoryNamesMainWindow.setObjectName("CategoryNamesMainWindow")
        CategoryNamesMainWindow.resize(588, 275)
        self.centralwidget = QtWidgets.QWidget(CategoryNamesMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.nextCategoryButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextCategoryButton.setGeometry(QtCore.QRect(354, 190, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.nextCategoryButton.setFont(font)
        self.nextCategoryButton.setObjectName("nextCategoryButton")
        self.saveAndExitButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveAndExitButton.setGeometry(QtCore.QRect(470, 190, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.saveAndExitButton.setFont(font)
        self.saveAndExitButton.setObjectName("saveAndExitButton")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 561, 171))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout.addWidget(self.horizontalSlider, 2, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.layoutWidget)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.gridLayout.addWidget(self.horizontalSlider_2, 3, 1, 1, 2)
        self.maleRadioButton = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.maleRadioButton.setFont(font)
        self.maleRadioButton.setObjectName("maleRadioButton")
        self.gridLayout.addWidget(self.maleRadioButton, 4, 1, 1, 1)
        self.femaleRadioButton = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.femaleRadioButton.setFont(font)
        self.femaleRadioButton.setObjectName("femaleRadioButton")
        self.gridLayout.addWidget(self.femaleRadioButton, 4, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 4)
        self.categoryNameLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.categoryNameLineEdit.setFont(font)
        self.categoryNameLineEdit.setObjectName("categoryNameLineEdit")
        self.gridLayout.addWidget(self.categoryNameLineEdit, 1, 1, 1, 3)
        self.lowerAgeLimitLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lowerAgeLimitLabel.setFont(font)
        self.lowerAgeLimitLabel.setObjectName("lowerAgeLimitLabel")
        self.gridLayout.addWidget(self.lowerAgeLimitLabel, 2, 3, 1, 1)
        self.upperAgeLimitLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upperAgeLimitLabel.sizePolicy().hasHeightForWidth())
        self.upperAgeLimitLabel.setSizePolicy(sizePolicy)
        self.upperAgeLimitLabel.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.upperAgeLimitLabel.setFont(font)
        self.upperAgeLimitLabel.setObjectName("upperAgeLimitLabel")
        self.gridLayout.addWidget(self.upperAgeLimitLabel, 3, 3, 1, 1)
        CategoryNamesMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CategoryNamesMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 588, 21))
        self.menubar.setObjectName("menubar")
        CategoryNamesMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CategoryNamesMainWindow)
        self.statusbar.setObjectName("statusbar")
        CategoryNamesMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(CategoryNamesMainWindow)
        self.horizontalSlider.valueChanged['int'].connect(self.lowerAgeLimitLabel.setNum)
        self.horizontalSlider_2.valueChanged['int'].connect(self.upperAgeLimitLabel.setNum)
        QtCore.QMetaObject.connectSlotsByName(CategoryNamesMainWindow)

    def retranslateUi(self, CategoryNamesMainWindow):
        _translate = QtCore.QCoreApplication.translate
        CategoryNamesMainWindow.setWindowTitle(_translate("CategoryNamesMainWindow", "MainWindow"))
        self.nextCategoryButton.setText(_translate("CategoryNamesMainWindow", "Next Category"))
        self.saveAndExitButton.setText(_translate("CategoryNamesMainWindow", "Save and Exit"))
        self.label_3.setText(_translate("CategoryNamesMainWindow", "Category Name:"))
        self.label.setText(_translate("CategoryNamesMainWindow", "Lower Age Limit:"))
        self.label_2.setText(_translate("CategoryNamesMainWindow", "Upper Age Limit:"))
        self.maleRadioButton.setText(_translate("CategoryNamesMainWindow", "Male"))
        self.femaleRadioButton.setText(_translate("CategoryNamesMainWindow", "Female"))
        self.label_4.setText(_translate("CategoryNamesMainWindow", "Insert your Categories"))
        self.lowerAgeLimitLabel.setText(_translate("CategoryNamesMainWindow", "0"))
        self.upperAgeLimitLabel.setText(_translate("CategoryNamesMainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CategoryNamesMainWindow = QtWidgets.QMainWindow()
    ui = Ui_CategoryNamesMainWindow()
    ui.setupCategoryNamesUi(CategoryNamesMainWindow)
    CategoryNamesMainWindow.show()
    sys.exit(app.exec_())
