from PyQt5 import QtCore, QtGui, QtWidgets
from categoryNameGUI import Ui_CategoryNamesMainWindow

class Ui_RaceNamesMainWindow(object):
    def setupRaceNamesUi(self, RaceNamesMainWindow):
        RaceNamesMainWindow.setObjectName("RaceNamesMainWindow")
        RaceNamesMainWindow.resize(500, 250)
        self.centralwidget = QtWidgets.QWidget(RaceNamesMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(6, 10, 491, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(210, 110, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.eventNameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.eventNameEdit.setGeometry(QtCore.QRect(102, 40, 391, 25))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(12)
        self.eventNameEdit.setFont(font)
        self.eventNameEdit.setObjectName("eventNameEdit")
        self.raceNameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.raceNameEdit.setGeometry(QtCore.QRect(102, 70, 391, 25))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(12)
        self.raceNameEdit.setFont(font)
        self.raceNameEdit.setObjectName("raceNameEdit")
        self.nextRaceButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextRaceButton.setGeometry(QtCore.QRect(280, 160, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.nextRaceButton.setFont(font)
        self.nextRaceButton.setObjectName("nextRaceButton")
        self.saveAndExitButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveAndExitButton.setGeometry(QtCore.QRect(390, 160, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.saveAndExitButton.setFont(font)
        self.saveAndExitButton.setObjectName("saveAndExitButton")
        self.saveAndExitButton.clicked.connect(self.saveNexit)
        self.raceDateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.raceDateEdit.setGeometry(QtCore.QRect(280, 101, 81, 31))
        self.raceDateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.raceDateEdit.setCalendarPopup(True)
        self.raceDateEdit.setObjectName("raceDateEdit")
        RaceNamesMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RaceNamesMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 21))
        self.menubar.setObjectName("menubar")
        RaceNamesMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RaceNamesMainWindow)
        self.statusbar.setObjectName("statusbar")
        RaceNamesMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RaceNamesMainWindow)
        QtCore.QMetaObject.connectSlotsByName(RaceNamesMainWindow)

    def retranslateUi(self, RaceNamesMainWindow):
        _translate = QtCore.QCoreApplication.translate
        RaceNamesMainWindow.setWindowTitle(_translate("RaceNamesMainWindow", "Define Race Names"))
        self.label.setText(_translate("RaceNamesMainWindow", "Insert Race Name"))
        self.label_2.setText(_translate("RaceNamesMainWindow", "Event Name:"))
        self.label_3.setText(_translate("RaceNamesMainWindow", "Race Name:"))
        self.label_4.setText(_translate("RaceNamesMainWindow", "Race Date"))
        self.nextRaceButton.setText(_translate("RaceNamesMainWindow", "Next Race"))
        self.saveAndExitButton.setText(_translate("RaceNamesMainWindow", "Save and Exit"))
        self.raceDateEdit.setDisplayFormat(_translate("RaceNamesMainWindow", "d/M/yyyy"))

    def saveNexit(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_CategoryNamesMainWindow()
        self.ui.setupCategoryNamesUi(self.window)
        self.window.show()
        RaceNamesMainWindow.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RaceNamesMainWindow = QtWidgets.QMainWindow()
    ui = Ui_RaceNamesMainWindow()
    ui.setupRaceNamesUi(RaceNamesMainWindow)
    RaceNamesMainWindow.show()
    sys.exit(app.exec_())
